# 利用GitHub Action自动构建多框架的docker镜像
name: Buildx_Danmuji_Docker_Test

on:
  # master分支的push操作会触发当前脚本的执行
  push:
    branches: [ main ]
  # master分支的pr操作会触发当前脚本的执行
#  pull_request:
#    branches: [ master ]
  # 定时任务,分时日月年,为国际标准时间16点,对应中国时间0点
#  schedule:
#    - cron: '0 16 * * *'
  # 点击star时开始任务
#  watch:
#    types: started


jobs:
  Buildx_Danmuji_Docker_Test:
    # 运行在Ubuntu系统上
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'test')"
    # 步骤
    steps:
      - name: Prepare
        id: prepare
        # IMAGE_NAME ： 镜像名称
        # VERSION ： 源码版本
        # DOCKERHUB_VERSION ： DockerHub 镜像版本
        # TAG_VERSION ： 标签版本
        # TAG_LATEST ： 最新版本
        run: |
          IMAGE_NAME=danmuji-test
          VERSION=$(curl -sX GET "https://api.github.com/repos/BanqiJane/Bilibili_Danmuji/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]')
          DOCKERHUB_VERSION=$(curl -sX GET "https://hub.docker.com/v2/repositories/zzcabc/danmuji-test/tags" | awk '{print $644;exit}' FS='[""]')
          TAG_VERSION="${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${VERSION}"
          TAG_LATEST="${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:latest"
          echo ::set-output name=tag_version::${TAG_VERSION}
          echo ::set-output name=tag_latest::${TAG_LATEST}
      # 切换到主分支
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # 初始化Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 登录到DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 初始化 JDK8 环境
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      # 使用Gradle编译构建同时命名danmuji.jar
      - name: Build with Gradle
        run: |
          sudo apt-get install git
          git clone https://github.com/BanqiJane/Bilibili_Danmuji.git
          cd Bilibili_Danmuji
          sudo chmod +x ./gradlew
          sudo ./gradlew build -x test
          sudo mv $(find build -type f -size +10M) ././danmuji.jar

     # 构建并推送
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          platforms:  linux/arm/v7
          file: ./Dockerfile.Alpine
          context: .
          push: true
          tags: |
            ${{ steps.prepare.outputs.tag_latest }}-arm32
            ${{ steps.prepare.outputs.tag_version }}-arm32


      # 构建并推送
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile.Debian
          context: .
          push: true
          tags: |
            ${{ steps.prepare.outputs.tag_latest }}
            ${{ steps.prepare.outputs.tag_version }}
